import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import Header from "@/components/Header";
import ThanhDieuHuong from "@/components/ThanhDieuHuong";
import ChromeToanSite from "@/components/ChromeToanSite";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Truyện chữ dịch",
  description: "Generated by create next app",
};

const SCRIPT_CHONG_FOUC = `
try {
  var t = localStorage.getItem('themeToanSite');
  if (t === 'giay' || t === 'toi') {
    document.documentElement.dataset.theme = t;
  }
} catch (e) {}
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Script id="chong-fouc-theme" strategy="beforeInteractive">
          {SCRIPT_CHONG_FOUC}
        </Script>
        <ChromeToanSite header={<Header />} dieuHuong={<ThanhDieuHuong />}>
          {children}
        </ChromeToanSite>
        <Analytics />
      </body>
    </html>
  );
}
